server:
  port: 8040

spring:
  datasource:
    username: "postgres"
    password: "qwerty"
    url: "jdbc:postgresql://localhost:5432/airlines"
    driver-class: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000